/*
# Seed: All remaining world countries (full international coverage)

## Changes
1. Insert the 140 remaining UN member states not already covered by the
   African countries seed (20260720200910_seed_plans_and_geography.sql),
   with ISO2 code, international dial code, and ISO 4217 currency code —
   sourced from the ISO 3166-1 / country-calling-code standards.
2. This makes onboarding's country selector cover all ~195 UN member
   states worldwide instead of only Africa, so hospitals/clinics anywhere
   (Americas, Europe, Asia, Oceania, Middle East) can self-onboard.

## Notes
- ON CONFLICT (iso2) DO NOTHING keeps this safe to re-run and safe against
  the existing African seed.
- Regions/districts/cities below country level are still only pre-seeded
  for Cameroon (see 20260720200910); other countries can add their own
  via the onboarding "add region/district/city" flow (Onboarding.tsx),
  same as any African country besides Cameroon already does today.

## Security
No policy changes — only data inserts into already-RLS-protected tables.
*/

INSERT INTO countries (name, iso2, phone_code, currency_code) VALUES
('Afghanistan','AF','+93','AFN'),
('Albania','AL','+355','ALL'),
('Andorra','AD','+376','EUR'),
('United Arab Emirates','AE','+971','AED'),
('Argentina','AR','+54','ARS'),
('Armenia','AM','+374','AMD'),
('Antigua and Barbuda','AG','+1268','XCD'),
('Australia','AU','+61','AUD'),
('Austria','AT','+43','EUR'),
('Azerbaijan','AZ','+994','AZN'),
('Belgium','BE','+32','EUR'),
('Bangladesh','BD','+880','BDT'),
('Bulgaria','BG','+359','BGN'),
('Bahrain','BH','+973','BHD'),
('Bahamas','BS','+1242','BSD'),
('Bosnia and Herzegovina','BA','+387','BAM'),
('Belarus','BY','+375','BYN'),
('Belize','BZ','+501','BZD'),
('Bolivia','BO','+591','BOB'),
('Brazil','BR','+55','BRL'),
('Barbados','BB','+1246','BBD'),
('Brunei','BN','+673','BND'),
('Bhutan','BT','+975','BTN'),
('Canada','CA','+1','CAD'),
('Switzerland','CH','+41','CHF'),
('Chile','CL','+56','CLP'),
('China','CN','+86','CNY'),
('Colombia','CO','+57','COP'),
('Costa Rica','CR','+506','CRC'),
('Cuba','CU','+53','CUC'),
('Cyprus','CY','+357','EUR'),
('Czechia','CZ','+420','CZK'),
('Germany','DE','+49','EUR'),
('Dominica','DM','+1767','XCD'),
('Denmark','DK','+45','DKK'),
('Dominican Republic','DO','+1','DOP'),
('Ecuador','EC','+593','USD'),
('Spain','ES','+34','EUR'),
('Estonia','EE','+372','EUR'),
('Finland','FI','+358','EUR'),
('Fiji','FJ','+679','FJD'),
('France','FR','+33','EUR'),
('Micronesia','FM','+691',''),
('United Kingdom','GB','+44','GBP'),
('Georgia','GE','+995','GEL'),
('Greece','GR','+30','EUR'),
('Grenada','GD','+1473','XCD'),
('Guatemala','GT','+502','GTQ'),
('Guyana','GY','+592','GYD'),
('Honduras','HN','+504','HNL'),
('Croatia','HR','+385','EUR'),
('Haiti','HT','+509','HTG'),
('Hungary','HU','+36','HUF'),
('Indonesia','ID','+62','IDR'),
('India','IN','+91','INR'),
('Ireland','IE','+353','EUR'),
('Iran','IR','+98','IRR'),
('Iraq','IQ','+964','IQD'),
('Iceland','IS','+354','ISK'),
('Israel','IL','+972','ILS'),
('Italy','IT','+39','EUR'),
('Jamaica','JM','+1876','JMD'),
('Jordan','JO','+962','JOD'),
('Japan','JP','+81','JPY'),
('Kazakhstan','KZ','+7','KZT'),
('Kyrgyzstan','KG','+996','KGS'),
('Cambodia','KH','+855','KHR'),
('Kiribati','KI','+686','AUD'),
('Saint Kitts and Nevis','KN','+1869','XCD'),
('South Korea','KR','+82','KRW'),
('Kuwait','KW','+965','KWD'),
('Laos','LA','+856','LAK'),
('Lebanon','LB','+961','LBP'),
('Saint Lucia','LC','+1758','XCD'),
('Liechtenstein','LI','+423','CHF'),
('Sri Lanka','LK','+94','LKR'),
('Lithuania','LT','+370','EUR'),
('Luxembourg','LU','+352','EUR'),
('Latvia','LV','+371','EUR'),
('Monaco','MC','+377','EUR'),
('Moldova','MD','+373','MDL'),
('Maldives','MV','+960','MVR'),
('Mexico','MX','+52','MXN'),
('Marshall Islands','MH','+692','USD'),
('North Macedonia','MK','+389','MKD'),
('Malta','MT','+356','EUR'),
('Myanmar','MM','+95','MMK'),
('Montenegro','ME','+382','EUR'),
('Mongolia','MN','+976','MNT'),
('Malaysia','MY','+60','MYR'),
('Nicaragua','NI','+505','NIO'),
('Netherlands','NL','+31','EUR'),
('Norway','NO','+47','NOK'),
('Nepal','NP','+977','NPR'),
('Nauru','NR','+674','AUD'),
('New Zealand','NZ','+64','NZD'),
('Oman','OM','+968','OMR'),
('Pakistan','PK','+92','PKR'),
('Panama','PA','+507','PAB'),
('Peru','PE','+51','PEN'),
('Philippines','PH','+63','PHP'),
('Palau','PW','+680','USD'),
('Papua New Guinea','PG','+675','PGK'),
('Poland','PL','+48','PLN'),
('North Korea','KP','+850','KPW'),
('Portugal','PT','+351','EUR'),
('Paraguay','PY','+595','PYG'),
('Qatar','QA','+974','QAR'),
('Romania','RO','+40','RON'),
('Russia','RU','+7','RUB'),
('Saudi Arabia','SA','+966','SAR'),
('Singapore','SG','+65','SGD'),
('Solomon Islands','SB','+677','SBD'),
('El Salvador','SV','+503','USD'),
('San Marino','SM','+378','EUR'),
('Serbia','RS','+381','RSD'),
('Suriname','SR','+597','SRD'),
('Slovakia','SK','+421','EUR'),
('Slovenia','SI','+386','EUR'),
('Sweden','SE','+46','SEK'),
('Syria','SY','+963','SYP'),
('Thailand','TH','+66','THB'),
('Tajikistan','TJ','+992','TJS'),
('Turkmenistan','TM','+993','TMT'),
('Timor-Leste','TL','+670','USD'),
('Tonga','TO','+676','TOP'),
('Trinidad and Tobago','TT','+1868','TTD'),
('Türkiye','TR','+90','TRY'),
('Tuvalu','TV','+688','AUD'),
('Ukraine','UA','+380','UAH'),
('Uruguay','UY','+598','UYU'),
('United States','US','+1','USD'),
('Uzbekistan','UZ','+998','UZS'),
('Vatican City','VA','+379','EUR'),
('Saint Vincent and the Grenadines','VC','+1784','XCD'),
('Venezuela','VE','+58','VES'),
('Vietnam','VN','+84','VND'),
('Vanuatu','VU','+678','VUV'),
('Samoa','WS','+685','WST'),
('Yemen','YE','+967','YER')
ON CONFLICT (iso2) DO NOTHING;