/*
# Health Cloud Billing & Subscription Schema

## Summary
Adds complete billing infrastructure: subscriptions, payments, invoices, grace period config, and subscription event audit trail.

## New Tables
1. `tenant_subscriptions` — active subscription per tenant (plan, billing cycle, status, payment gateway, auto-renew)
2. `payments` — immutable payment ledger (amount, gateway, status, gateway tx id)
3. `billing_invoices` — generated invoices with auto-numbered invoice_number (INV-YYYYMMDD-NNNN)
4. `grace_period_config` — configurable grace days (global default=3, per-tenant override)
5. `subscription_events` — append-only lifecycle event log

## Security
- RLS enabled on all tables
- tenant_subscriptions/payments/invoices: tenant members can SELECT; super admin only INSERT/UPDATE
- grace_period_config: global row readable by all authenticated; super admin for CRUD
- subscription_events: tenant members SELECT; append-only (no UPDATE/DELETE)

## Notes
1. All enum types are created idempotently
2. Invoice numbers auto-generated by trigger (BEFORE INSERT)
3. Global grace period default (3 days) seeded on first run
4. updated_at maintained by trigger on all mutable tables
*/

-- ENUM TYPES
DO $$ BEGIN CREATE TYPE billing_cycle_enum AS ENUM ('monthly', 'yearly'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE subscription_status_enum AS ENUM ('active', 'cancelled', 'suspended', 'past_due', 'trialing'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE payment_gateway_enum AS ENUM ('stripe', 'flutterwave', 'paystack', 'orange_money', 'mtn_momo', 'visa', 'mastercard', 'bank_transfer'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE payment_status_enum AS ENUM ('pending', 'succeeded', 'failed', 'refunded'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE invoice_status_enum AS ENUM ('draft', 'open', 'paid', 'void', 'uncollectible'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE subscription_event_type_enum AS ENUM ('trial_started', 'trial_ending_soon', 'trial_expired', 'subscription_created', 'payment_succeeded', 'payment_failed', 'subscription_cancelled', 'grace_period_started', 'grace_period_expired', 'subscription_upgraded', 'subscription_downgraded', 'subscription_renewed'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- TRIGGER: updated_at
CREATE OR REPLACE FUNCTION fn_set_updated_at() RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END; $$;

-- 1. tenant_subscriptions
CREATE TABLE IF NOT EXISTS tenant_subscriptions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  plan_id uuid NOT NULL REFERENCES subscription_plans(id) ON DELETE RESTRICT,
  billing_cycle billing_cycle_enum NOT NULL,
  start_date date NOT NULL,
  end_date date,
  status subscription_status_enum NOT NULL DEFAULT 'active',
  payment_gateway payment_gateway_enum,
  next_billing_date date,
  auto_renew boolean NOT NULL DEFAULT true,
  cancelled_at timestamptz,
  cancellation_reason text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_ts_tenant_id ON tenant_subscriptions(tenant_id);
CREATE INDEX IF NOT EXISTS idx_ts_status ON tenant_subscriptions(status);
CREATE INDEX IF NOT EXISTS idx_ts_next_billing ON tenant_subscriptions(next_billing_date) WHERE status = 'active';
DROP TRIGGER IF EXISTS trg_ts_updated_at ON tenant_subscriptions;
CREATE TRIGGER trg_ts_updated_at BEFORE UPDATE ON tenant_subscriptions FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
ALTER TABLE tenant_subscriptions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "ts_select" ON tenant_subscriptions;
CREATE POLICY "ts_select" ON tenant_subscriptions FOR SELECT TO authenticated USING (is_tenant_member(tenant_id) OR is_super_admin());
DROP POLICY IF EXISTS "ts_insert" ON tenant_subscriptions;
CREATE POLICY "ts_insert" ON tenant_subscriptions FOR INSERT TO authenticated WITH CHECK (is_super_admin());
DROP POLICY IF EXISTS "ts_update" ON tenant_subscriptions;
CREATE POLICY "ts_update" ON tenant_subscriptions FOR UPDATE TO authenticated USING (is_super_admin()) WITH CHECK (is_super_admin());

-- 2. payments
CREATE TABLE IF NOT EXISTS payments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  subscription_id uuid REFERENCES tenant_subscriptions(id) ON DELETE SET NULL,
  amount numeric(12,2) NOT NULL CHECK (amount >= 0),
  currency char(3) NOT NULL DEFAULT 'USD',
  gateway payment_gateway_enum,
  gateway_tx_id text,
  status payment_status_enum NOT NULL DEFAULT 'pending',
  paid_at timestamptz,
  invoice_url text,
  metadata jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_pay_tenant_id ON payments(tenant_id);
CREATE INDEX IF NOT EXISTS idx_pay_sub_id ON payments(subscription_id);
CREATE INDEX IF NOT EXISTS idx_pay_status ON payments(status);
CREATE INDEX IF NOT EXISTS idx_pay_gtx ON payments(gateway_tx_id) WHERE gateway_tx_id IS NOT NULL;
DROP TRIGGER IF EXISTS trg_pay_updated_at ON payments;
CREATE TRIGGER trg_pay_updated_at BEFORE UPDATE ON payments FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "pay_select" ON payments;
CREATE POLICY "pay_select" ON payments FOR SELECT TO authenticated USING (is_tenant_member(tenant_id) OR is_super_admin());
DROP POLICY IF EXISTS "pay_insert" ON payments;
CREATE POLICY "pay_insert" ON payments FOR INSERT TO authenticated WITH CHECK (is_super_admin());
DROP POLICY IF EXISTS "pay_update" ON payments;
CREATE POLICY "pay_update" ON payments FOR UPDATE TO authenticated USING (is_super_admin()) WITH CHECK (is_super_admin());

-- 3. billing_invoices
CREATE TABLE IF NOT EXISTS billing_invoices (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  invoice_number text UNIQUE NOT NULL DEFAULT '',
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  subscription_id uuid REFERENCES tenant_subscriptions(id) ON DELETE SET NULL,
  amount_due numeric(12,2) NOT NULL CHECK (amount_due >= 0),
  amount_paid numeric(12,2) NOT NULL DEFAULT 0,
  due_date date NOT NULL,
  paid_at timestamptz,
  status invoice_status_enum NOT NULL DEFAULT 'draft',
  line_items jsonb NOT NULL DEFAULT '[]',
  pdf_url text,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION fn_generate_invoice_number() RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE
  v_date text := to_char(now(), 'YYYYMMDD');
  v_seq bigint;
BEGIN
  SELECT COALESCE(MAX((regexp_match(invoice_number, 'INV-' || v_date || '-(\d+)'))[1]::bigint), 0)
  INTO v_seq FROM billing_invoices WHERE invoice_number LIKE 'INV-' || v_date || '-%';
  NEW.invoice_number := 'INV-' || v_date || '-' || lpad((v_seq + 1)::text, 4, '0');
  RETURN NEW;
END; $$;

DROP TRIGGER IF EXISTS trg_inv_number ON billing_invoices;
CREATE TRIGGER trg_inv_number BEFORE INSERT ON billing_invoices FOR EACH ROW WHEN (NEW.invoice_number = '' OR NEW.invoice_number IS NULL) EXECUTE FUNCTION fn_generate_invoice_number();

CREATE INDEX IF NOT EXISTS idx_inv_tenant_id ON billing_invoices(tenant_id);
CREATE INDEX IF NOT EXISTS idx_inv_status ON billing_invoices(status);
DROP TRIGGER IF EXISTS trg_inv_updated_at ON billing_invoices;
CREATE TRIGGER trg_inv_updated_at BEFORE UPDATE ON billing_invoices FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
ALTER TABLE billing_invoices ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "inv_select" ON billing_invoices;
CREATE POLICY "inv_select" ON billing_invoices FOR SELECT TO authenticated USING (is_tenant_member(tenant_id) OR is_super_admin());
DROP POLICY IF EXISTS "inv_insert" ON billing_invoices;
CREATE POLICY "inv_insert" ON billing_invoices FOR INSERT TO authenticated WITH CHECK (is_super_admin());
DROP POLICY IF EXISTS "inv_update" ON billing_invoices;
CREATE POLICY "inv_update" ON billing_invoices FOR UPDATE TO authenticated USING (is_super_admin()) WITH CHECK (is_super_admin());

-- 4. grace_period_config
CREATE TABLE IF NOT EXISTS grace_period_config (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid REFERENCES tenants(id) ON DELETE CASCADE,
  grace_days integer NOT NULL DEFAULT 3 CHECK (grace_days > 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uidx_gpc_global ON grace_period_config ((tenant_id IS NULL)) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uidx_gpc_tenant ON grace_period_config (tenant_id) WHERE tenant_id IS NOT NULL;
DROP TRIGGER IF EXISTS trg_gpc_updated_at ON grace_period_config;
CREATE TRIGGER trg_gpc_updated_at BEFORE UPDATE ON grace_period_config FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
ALTER TABLE grace_period_config ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "gpc_select" ON grace_period_config;
CREATE POLICY "gpc_select" ON grace_period_config FOR SELECT TO authenticated USING (tenant_id IS NULL OR is_super_admin());
DROP POLICY IF EXISTS "gpc_insert" ON grace_period_config;
CREATE POLICY "gpc_insert" ON grace_period_config FOR INSERT TO authenticated WITH CHECK (is_super_admin());
DROP POLICY IF EXISTS "gpc_update" ON grace_period_config;
CREATE POLICY "gpc_update" ON grace_period_config FOR UPDATE TO authenticated USING (is_super_admin()) WITH CHECK (is_super_admin());
DROP POLICY IF EXISTS "gpc_delete" ON grace_period_config;
CREATE POLICY "gpc_delete" ON grace_period_config FOR DELETE TO authenticated USING (is_super_admin());

-- 5. subscription_events
CREATE TABLE IF NOT EXISTS subscription_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  subscription_id uuid REFERENCES tenant_subscriptions(id) ON DELETE SET NULL,
  event_type subscription_event_type_enum NOT NULL,
  metadata jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_se_tenant_id ON subscription_events(tenant_id);
CREATE INDEX IF NOT EXISTS idx_se_event_type ON subscription_events(event_type);
CREATE INDEX IF NOT EXISTS idx_se_tenant_created ON subscription_events(tenant_id, created_at DESC);
ALTER TABLE subscription_events ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "se_select" ON subscription_events;
CREATE POLICY "se_select" ON subscription_events FOR SELECT TO authenticated USING (is_tenant_member(tenant_id) OR is_super_admin());
DROP POLICY IF EXISTS "se_insert" ON subscription_events;
CREATE POLICY "se_insert" ON subscription_events FOR INSERT TO authenticated WITH CHECK (is_super_admin());

-- SEED: global grace period default
INSERT INTO grace_period_config (tenant_id, grace_days) VALUES (NULL, 3) ON CONFLICT DO NOTHING;

-- Add grace_period_ends_at column to tenants if missing
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='tenants' AND column_name='grace_period_ends_at') THEN
    ALTER TABLE tenants ADD COLUMN grace_period_ends_at timestamptz;
  END IF;
END $$;

-- Update super admin emails list
UPDATE profiles SET is_super_admin = true
WHERE id IN (
  SELECT id FROM auth.users
  WHERE lower(email) IN ('vincentnogue2@gmail.com', 'vincentnogue@yahoo.com', 'webdxb1@gmail.com', 'liyahjoha@gmail.com')
);
